#!/usr/bin/env python3

import random
import sys

def time24f(hour: int, minute: int) -> str:
    str_hour_24 = '{0:02d}'.format(hour)
    str_minute = '{0:02d}'.format(minute)

    return str_hour_24 + ':' + str_minute

def time12f(hour: int, minute: int) -> str:
    str_minute = '{0:02d}'.format(minute)

    if hour == 0:
        hour_12 = 12
        am_pm = 'am'
    elif hour > 12:
        hour_12 = hour - 12
        am_pm = 'pm'
    elif hour == 12:
        hour_12 = 12
        am_pm = 'pm'
    else:
        hour_12 = hour
        am_pm = 'am'

    return str(hour_12) + ':' + str_minute + ' ' + am_pm

def get_random_times(): # -> list[tuple[str, str]]
    hours = list(range(0, 24))
    minutes = list(range(0, 60))

    random.shuffle(hours)
    random.shuffle(minutes)

    times = []

    for i in range(len(hours)):
        str_24 = time24f(hours[i], minutes[i])
        str_12 = time12f(hours[i], minutes[i])
        times.append((str_24, str_12))

    return times

def drill_question(question: str, answer: str):
    while True:
        print('Q: ' + question)
        try:
            line = input('A: ')
        except KeyboardInterrupt:
            print('')
            sys.exit(0)

        if line.strip() == answer:
            print('Correct.')
            break
        else:
            print('Try again.')

if __name__ == '__main__':
    while True:
        times = get_random_times()
        for time in times:
            t24, t12 = time
            drill_question(t12 + ' -> 24-hour time', t24)
